nome = input("digite seu nome: ")
print("Olá ", nome, ", seja bem vindo ao nosso curso de Python, esse é o exercicio 1")
print(nome,", agora vamos fazer o exercicio 2: ")
a = (10 + 20 * 30)
b = (4**2 / 30)
c = ((9**4 + 2) * 6 - 1)
print("a resposta da equação 2.A é: ", a)
print("a resposta da equação 2.B é: ", b)
print("a resposta da equação 2.C é: ", c)
print("se voce acertou todas as equaçoes parabens, agora vamos ver uma outra forma da fazer essas equaçoes. ")
print("a resposta da equação 2.A é: ", (10+20*30))
print("a resposta da equação 2.B é: ", (4**2 / 30))
print("a resposta da equação 2.C é: ", ((9**4 + 2) * 6 - 1))
print(nome, ", voce sabia que voce pode formatar esses valores? Vamos ver:  ")
print(f"a resposta da equação 2.A é: {(10+20*30):6.3f} nesse exemplo usamos 6 casas com 3 decimais")
print(f"a resposta da equação 2.B é: {(4**2 / 30):5.2f} nesse exemplo usamos 5 casas com 2 decimais")
print(f"a resposta da equação 2.C é: {((9**4 + 2) * 6 - 1):6.2f} nesse exemplo usamos 6 casa com 2 decimais")
print(nome, ", viu como tem diferentes formas de fazer uma equação em python? e ambas simples")
print(nome, ", agora vamos fazer o exercicio 3: ")
d = (0.10 * 3 * 10 ** 2 + 1 - 10 * 4 / 2)
print("a resposta da equação 3, é: ", d)
print("voce pode usar as mesmas formas de formatacao e calculos do exercicios 2", end= "\t nesse caso usei (0.10) para representar 10porcento")
print(nome, ", agora vamos fazer o exercicio 4: ")
e = 3
f = 5
g = ((2*e) * (3*f))
print("a resposta da equacao 4, é: ", g)
print("a resposta da equacao 4. é: ", ((2*e)*(3*f)))
print(nome, ", agora vamos fazer o exercicio 5: ")
h = int(input("digite o primeiro valor: "))
i = int(input("digite o segundo valor: "))
j = int(input("digite o terceiro valor: "))
k = (h+i+j)
print("a resposta da equacao 5, é: ", k)
print("a resposta da equacao 5, é: ", h+i+j)
print(" se voce não declarar que a varial é do tipo int, o sistema vai concatenar os valores, ficaria assim: ")
l = input("digite o primeiro valor: ")
m = input("digite o segundo valor: ")
n = input("digite o terceiro valor: ")
print("o valor concatenado é: ", l+m+n)
print(nome, ", agora vamos fazer o exercicio 6: ")
o = float(input("digite o valor do salario: R$"))
p = int(input("digite a porcentagem do aumento: "))
q = (p/100)
r = (o*q)
print("o valor do seu aumento será de: R$",r)
print("o valor do seu novo salario é de: R$", r+o)
print(f"voce poderia fazer todos os calculos direto no print, assim: R${((p/100)*o)+o:6.2f}")

