import string
a = input("digite um nome: ")
print(len(a))
print(a[2])
print(a[3:6])
print(a[4:])
print(a[:4])
print(a[-3])

print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.count("r"))
print(a.count("R"))
print(a.strip())
print(a.split())
print(a.startswith("R"))
print(a.startswith("r"))
print(a.endswith("z"))
print(a.replace("souza", "santos"))
print(a.center(10))
print(a.find("so"))
print(a.find("Jacare"))

